version: 2.1

executors:
 default:
  working_directory: ~/repo
  description: The official CircleCI Ruby Docker image
  docker:
       - image: circleci/ruby:2.7.1

caches:
  - &bundle_cache_full v2-repo-{{ checksum "Gemfile.lock"}}
  - &bundle_cache v2-repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - run:
          name: Install dependencies
          command: |
            gem install bundler -v 2.2.3 
            bundler install 
      - save_cache:
          key: *bundle_cache_full
          paths: 
            - vendor/bundle
  run_fasterer:
    steps:
      - run:
          name: fasterer
          command: bundle exec fasterer
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
  run_specs:
    steps:
      - run:
          name: run specs
          command: bundle exec rspec --format progress spec

jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
  fasterer:
    executor: default
    steps:
      - defaults
      - run_fasterer
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - fasterer
      - lintering
      - run_specs:
          requires:
            - lintering
